### ISSUE TITLE
Design for content sub navigation

### ISSUE THREAD

**Issue by zoepage** [webcompat/design#48]
For context:
https://github.com/webcompat/webcompat.com/issues/1149#issuecomment-284589695

https://webcompat.com/contributors

We need a design suggestion / idea for the content sub navigation as you can see below. 

<img src="https://cloud.githubusercontent.com/assets/4382193/23637110/87675074-028e-11e7-862b-bef7f7c8a955.png" />

<img src="https://cloud.githubusercontent.com/assets/4382193/23636977/b9222cac-028d-11e7-9465-7aee2090c733.png" />

As you can see in the mock ups, we have an option for a sub navigation for the content. 

<img src="https://cloud.githubusercontent.com/assets/4382193/22677285/4828c828-eca6-11e6-8437-46612569f369.png" />

There is also an idea for the mobile version. 

There are 2 challenges to tackle to make this concept work. 

1. We need it to fit with the "new" design that can be seen here: http://webcompat.github.io/design/
2. We are a bit limited due to the grid. We thought to use the [1:2] grid -> [nav : content] and go with it's behavior on mobile.

If there are other ideas, its also great. Not stuck on the ones shown above.

What do you think @aminalhazwani ?

Would be great if this would also benefit https://webcompat.com/contributors this, as the opening and closing topics definitely need to go. :)

**Comment by aminalhazwani** [comment]
@zoepage I can help on this one! Is there a sketch file I should work on?

**Comment by zoepage** [comment]
Just uploaded! https://github.com/webcompat/design/blob/master/website_modules/form.sketch

**Comment by aminalhazwani** [comment]
Following the styles of the issues filters I designed a side navigation that is always visible on desktop and that it is collapse by default on mobile but that can be opened. 

On desktop I would suggest to display it on the right so that you maintain a straight left reading edge but I'll leave the final call to you! The current section is highlighted by the yellow edge and the bold typography. On scroll the side navigation can be set sticky to the top. The highlight can change on scroll as well so that the yellow border always highlights the current section.

On mobile the navigation can be positioned right after the title page so that users can inspect the page contents with one tap and then choose to jump to a specific section or simply scroll the page down. 

This side navigation introduces a new color `#888` that can be used for secondary texts. This color is AA compliant, this is why I set the typography "Table of contents" to bold. All the other colors are system compliant. The side navigation introduces also a smaller font size `0.875em` so that the navigation has a lower hierarchy than the content.

<img width="1110" alt="screen shot 2017-11-16 at 2 43 10 pm" src="https://user-images.githubusercontent.com/1721875/32894726-f52df06e-cadd-11e7-9109-7564c1986c45.png">
